title: Your Site Title
description: >- # this means to ignore newlines until "baseurl:"
  A description of your site.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourusername.github.io" # the base hostname & protocol for your site
theme: minima # you can specify other themes available
